In [1]:
# Dependencies
from sklearn import tree
import pandas as pd
import os 
from sklearn.model_selection import train_test_split

In [2]:
# Load in data
df = pd.read_csv('data_sets/drafted_data.csv')
df.head()

,LEAGUE,PLAYER_ID,POSITION,SEASON,AGE_SEPT_15,GP,G,A,TP,PPG,...,SEASON_>20GP,CUM_GP,ONLY_1_SEASON,MIN_3_SEASONS,DY_STATUS,SHOOTS,DRAFTED,NHL_PPG,NHL_GP,NHL_DV
0,WHL,100577/richard-nejezchleb,F,2015,21.369444,49,20,31,51,1.040816,...,3,150,0,1,DY+3,L,Yes,0.000000,0,0
1,QMJHL,100867/jan-kostalek,D,2015,20.577778,57,7,36,43,0.754386,...,3,160,0,1,DY+2,R,Yes,0.000000,0,0
2,OHL,101221/dominik-kubalik,F,2014,19.066667,59,18,11,29,0.491525,...,2,126,0,0,DY+1,L,Yes,0.000000,0,0
3,WHL,10123/denis-rehak,D,2004,19.336111,25,0,3,3,0.120000,...,1,25,1,0,DY+1,L,Yes,0.000000,0,0
4,USHL,101430/nathan-walker,F,2013,19.605556,29,7,20,27,0.931034,...,1,29,1,0,DY+1,L,Yes,0.166667,12,1

In [3]:
# Dropping columns that won't impact the prediction model(player ID, season) and those which will give it the answer(NHL games played and points)
df = df.drop(['PLAYER_ID', 'SEASON', 'NHL_PPG','NHL_GP','DRAFTED','LEAGUE'], axis=1)
df.head()

,POSITION,AGE_SEPT_15,GP,G,A,TP,PPG,SEASON_NO,SEASON_>20GP,CUM_GP,ONLY_1_SEASON,MIN_3_SEASONS,DY_STATUS,SHOOTS,NHL_DV
0,F,21.369444,49,20,31,51,1.040816,3,3,150,0,1,DY+3,L,0
1,D,20.577778,57,7,36,43,0.754386,3,3,160,0,1,DY+2,R,0
2,F,19.066667,59,18,11,29,0.491525,2,2,126,0,0,DY+1,L,0
3,D,19.336111,25,0,3,3,0.120000,1,1,25,1,0,DY+1,L,0
4,F,19.605556,29,7,20,27,0.931034,1,1,29,1,0,DY+1,L,1

In [4]:
# Convert Position to int (Forward = 0, Defense = 1, Goalie= 2)
df.POSITION[df.POSITION == 'F'] = 0
df.POSITION[df.POSITION == 'D'] = 1
df.POSITION[df.POSITION == 'G'] = 2
df.head()

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.

,POSITION,AGE_SEPT_15,GP,G,A,TP,PPG,SEASON_NO,SEASON_>20GP,CUM_GP,ONLY_1_SEASON,MIN_3_SEASONS,DY_STATUS,SHOOTS,NHL_DV
0,0,21.369444,49,20,31,51,1.040816,3,3,150,0,1,DY+3,L,0
1,1,20.577778,57,7,36,43,0.754386,3,3,160,0,1,DY+2,R,0
2,0,19.066667,59,18,11,29,0.491525,2,2,126,0,0,DY+1,L,0
3,1,19.336111,25,0,3,3,0.120000,1,1,25,1,0,DY+1,L,0
4,0,19.605556,29,7,20,27,0.931034,1,1,29,1,0,DY+1,L,1

In [5]:
# Convert shooting side to int (left = 0, right = 1)
df.SHOOTS[df.SHOOTS == 'L'] = 0
df.SHOOTS[df.SHOOTS == 'R'] = 1
df.head()

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until

,POSITION,AGE_SEPT_15,GP,G,A,TP,PPG,SEASON_NO,SEASON_>20GP,CUM_GP,ONLY_1_SEASON,MIN_3_SEASONS,DY_STATUS,SHOOTS,NHL_DV
0,0,21.369444,49,20,31,51,1.040816,3,3,150,0,1,DY+3,0,0
1,1,20.577778,57,7,36,43,0.754386,3,3,160,0,1,DY+2,1,0
2,0,19.066667,59,18,11,29,0.491525,2,2,126,0,0,DY+1,0,0
3,1,19.336111,25,0,3,3,0.120000,1,1,25,1,0,DY+1,0,0
4,0,19.605556,29,7,20,27,0.931034,1,1,29,1,0,DY+1,0,1

In [12]:
# Convert Draft year to int (draft year = 2, dy-2 = 0, etc)
df.DY_STATUS[df.DY_STATUS == 'DY-2'] = 0
df.DY_STATUS[df.DY_STATUS == 'DY-1'] = 1
df.DY_STATUS[df.DY_STATUS == 'DY'] = 2
df.DY_STATUS[df.DY_STATUS == 'DY+1'] = 3
df.DY_STATUS[df.DY_STATUS == 'DY+2'] = 4
df.DY_STATUS[df.DY_STATUS == 'DY+3'] = 5
df.head(250)

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  import sys

,POSITION,AGE_SEPT_15,GP,G,A,TP,PPG,SEASON_NO,SEASON_>20GP,CUM_GP,ONLY_1_SEASON,MIN_3_SEASONS,DY_STATUS,SHOOTS,NHL_DV
0,0,21.369444,49,20,31,51,1.040816,3,3,150,0,1,5,0,0
1,1,20.577778,57,7,36,43,0.754386,3,3,160,0,1,4,1,0
2,0,19.066667,59,18,11,29,0.491525,2,2,126,0,0,3,0,0
3,1,19.336111,25,0,3,3,0.120000,1,1,25,1,0,3,0,0
4,0,19.605556,29,7,20,27,0.931034,1,1,29,1,0,3,0,1
5,1,19.955556,68,14,54,68,1.000000,1,1,68,1,0,3,0,1
6,0,18.013889,68,28,40,68,1.000000,2,2,134,0,0,2,0,1
7,0,20.066667,59,12,37,49,0.830508,4,4,249,0,1,4,1,1
8,1,20.116667,43,13,35,48,1.116279,4,4,253,0,1,4,0,1
9,0,21.619444,56,20,33,53,0.946429,5,5,312,0,1,5,1,0
10,1,20.944444,59,3,21,24,0.406780,3,2,133,0,0,4,1,0
11,0,19.691667,61,24,33,57,0.934426,1,1,61,1,0,3,1,1
12,0,18.186111,18,3,7,10,0.555556,2,0,40,0,0,2,0,1
13,0,20.427778,56,27,28,55,0.982143,4,4,196,0,1,4,1,1
14,0,20.216667,63,13,17,30,0.476190,3,3,183,0,1,4,0,1
15,0,20.613889,68,41,56,97,1.426471,4,3,208,0,1,4,0,1
16,0,18.716667,56,30,47,77,1.375000,2,2,113,0,0,2,0,1
17,1,19.458333,66,16,57,73,1.106061,3,3,177,0,1,3,0,1
18,1,20.338889,51,14,32,46,0.901961,2,2,115,0,0,4,0,1
19,0,19.716667,64,31,41,72,1.125000,3,3,189,0,1,3,0,1
20,1,19.950000,23,4,6,10,0.434783,3,3,160,0,1,3,1,1
21,1,20.100000,62,16,26,42,0.677419,3,3,190,0,1,4,0,1
22,1,20.375000,57,10,51,61,1.070175,4,4,250,0,1,4,0,1
23,0,19.705556,27,23,15,38,1.407407,3,3,164,0,1,3,1,1
24,1,20.975000,64,6,25,31,0.484375,3,3,200,0,1,4,0,0
25,1,20.016667,66,25,59,84,1.272727,1,1,66,1,0,4,0,1
26,0,19.447222,55,47,33,80,1.454545,1,1,55,1,0,3,1,1
27,0,20.944444,58,19,15,34,0.586207,4,4,253,0,1,4,0,1
28,0,19.713889,60,35,33,68,1.133333,4,3,162,0,1,3,1,1
29,0,20.302778,66,29,64,93,1.409091,4,4,212,0,1,4,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
220,0,19.830556,63,32,36,68,1.079365,4,4,252,0,1,3,1,1
221,0,20.369444,29,8,27,35,1.206897,4,4,205,0,1,4,0,0
222,1,20.494444,68,11,38,49,0.720588,3,3,204,0,1,4,0,1
223,1,20.652778,60,13,37,50,0.833333,4,4,245,0,1,4,1,1
224,1,20.350000,63,13,41,54,0.857143,4,4,227,0,1,4,0,1
225,1,20.472222,63,8,41,49,0.777778,4,4,233,0,1,4,0,1
226,1,18.869444,57,7,21,28,0.491228,3,3,189,0,1,2,1,1
227,0,21.269444,68,31,62,93,1.367647,5,5,330,0,1,5,1,0
228,0,20.216667,29,15,33,48,1.655172,4,4,193,0,1,4,1,0
229,1,20.002778,61,10,13,23,0.377049,2,2,118,0,0,4,0,0
230,0,19.577778,49,14,11,25,0.510204,1,1,49,1,0,3,0,1
231,0,19.375000,54,30,31,61,1.129630,2,2,110,0,0,3,0,1
232,0,19.027778,48,21,23,44,0.916667,1,1,48,1,0,3,1,1
233,0,19.108333,60,30,30,60,1.000000,1,1,60,1,0,3,1,1
234,0,19.344444,57,23,29,52,0.912281,2,2,115,0,0,3,1,1
235,0,18.688889,60,24,33,57,0.950000,1,1,60,1,0,2,1,0
236,1,18.861111,13,1,3,4,0.307692,1,0,13,1,0,2,1,1
237,0,19.372222,57,28,41,69,1.210526,2,2,87,0,0,3,1,1
238,1,19.952778,60,13,34,47,0.783333,2,2,97,0,0,3,1,0
239,0,19.683333,60,21,26,47,0.783333,2,2,80,0,0,3,0,1
240,0,19.541667,58,29,30,59,1.017241,2,2,102,0,0,3,0,1
241,0,20.577778,70,37,33,70,1.000000,3,3,212,0,1,4,0,1
242,1,20.630556,49,3,32,35,0.714286,4,4,181,0,1,4,1,0
243,1,19.008333,9,0,4,4,0.444444,1,0,9,1,0,3,0,1
244,0,18.816667,21,4,11,15,0.714286,1,1,21,1,0,2,1,1
245,0,21.583333,56,18,46,64,1.142857,1,1,56,1,0,5,1,0
246,0,18.652778,12,8,1,9,0.750000,1,0,12,1,0,2,1,0
247,1,20.605556,68,11,24,35,0.514706,4,4,271,0,1,4,0,1
248,0,20.619444,71,30,19,49,0.690141,4,4,237,0,1,4,1,0
249,1,20.572222,71,10,43,53,0.746479,4,4,249,0,1,4,0,0

In [7]:
# split data into inputs and outputs
data = df.values
inputs = data[:, 0:14]
outputs = data[:, 14]

In [8]:
# split data into inputs and outputs

outcomes = df['NHL_DV']
outcomes.head()

input_factors = df.drop(['NHL_DV'], axis = 1)
input_factors.head()
feature_names = input_factors.columns

In [9]:
# Create Train/test groups
input_train, input_test, output_train, output_test = train_test_split(input_factors, outcomes, random_state=42)

In [10]:
# decision tree
clf = tree.DecisionTreeClassifier()
clf = clf.fit(input_train, output_train)
clf.score(input_test, output_test)

ValueError: could not convert string to float: '-'