In [49]:
#  Dependencies
%matplotlib inline
import matplotlib.pyplot as plt
import pandas as pd
import os
import numpy as np

In [31]:
# Load in data
df = pd.read_csv('data_sets/drafted_data.csv')
df.head()

,LEAGUE,PLAYER_ID,POSITION,SEASON,AGE_SEPT_15,GP,G,A,TP,PPG,...,SEASON_>20GP,CUM_GP,ONLY_1_SEASON,MIN_3_SEASONS,DY_STATUS,SHOOTS,DRAFTED,NHL_PPG,NHL_GP,NHL_DV
0,WHL,100577/richard-nejezchleb,F,2015,21.369444,49,20,31,51,1.040816,...,3,150,0,1,DY+3,L,Yes,0.000000,0,0
1,QMJHL,100867/jan-kostalek,D,2015,20.577778,57,7,36,43,0.754386,...,3,160,0,1,DY+2,R,Yes,0.000000,0,0
2,OHL,101221/dominik-kubalik,F,2014,19.066667,59,18,11,29,0.491525,...,2,126,0,0,DY+1,L,Yes,0.000000,0,0
3,WHL,10123/denis-rehak,D,2004,19.336111,25,0,3,3,0.120000,...,1,25,1,0,DY+1,L,Yes,0.000000,0,0
4,USHL,101430/nathan-walker,F,2013,19.605556,29,7,20,27,0.931034,...,1,29,1,0,DY+1,L,Yes,0.166667,12,1

In [32]:
# Function to convert League from string into int
def league_int(x):
    if x.LEAGUE == 'WHL':
        return 0
    elif x.LEAGUE == 'QMJHL':
        return 1
    elif x.LEAGUE == 'OHL':
        return 2
    elif x.LEAGUE == 'USHL':
        return 3

In [33]:
#apply funct to set and show headto see league is now int
df['LEAGUE'] = df.apply(league_int, axis=1)
df.head()

,LEAGUE,PLAYER_ID,POSITION,SEASON,AGE_SEPT_15,GP,G,A,TP,PPG,...,SEASON_>20GP,CUM_GP,ONLY_1_SEASON,MIN_3_SEASONS,DY_STATUS,SHOOTS,DRAFTED,NHL_PPG,NHL_GP,NHL_DV
0,0,100577/richard-nejezchleb,F,2015,21.369444,49,20,31,51,1.040816,...,3,150,0,1,DY+3,L,Yes,0.000000,0,0
1,1,100867/jan-kostalek,D,2015,20.577778,57,7,36,43,0.754386,...,3,160,0,1,DY+2,R,Yes,0.000000,0,0
2,2,101221/dominik-kubalik,F,2014,19.066667,59,18,11,29,0.491525,...,2,126,0,0,DY+1,L,Yes,0.000000,0,0
3,0,10123/denis-rehak,D,2004,19.336111,25,0,3,3,0.120000,...,1,25,1,0,DY+1,L,Yes,0.000000,0,0
4,3,101430/nathan-walker,F,2013,19.605556,29,7,20,27,0.931034,...,1,29,1,0,DY+1,L,Yes,0.166667,12,1

In [34]:
# Create a function to coonvert position string to int
def position_int(x):
    if x.POSITION == 'F':
        return 0
    elif x.POSITION == 'D':
        return 1

In [35]:
# Apply position conversion function adn display head to show it worked properly
df['POSITION'] = df.apply(position_int, axis=1)
df.head()

,LEAGUE,PLAYER_ID,POSITION,SEASON,AGE_SEPT_15,GP,G,A,TP,PPG,...,SEASON_>20GP,CUM_GP,ONLY_1_SEASON,MIN_3_SEASONS,DY_STATUS,SHOOTS,DRAFTED,NHL_PPG,NHL_GP,NHL_DV
0,0,100577/richard-nejezchleb,0,2015,21.369444,49,20,31,51,1.040816,...,3,150,0,1,DY+3,L,Yes,0.000000,0,0
1,1,100867/jan-kostalek,1,2015,20.577778,57,7,36,43,0.754386,...,3,160,0,1,DY+2,R,Yes,0.000000,0,0
2,2,101221/dominik-kubalik,0,2014,19.066667,59,18,11,29,0.491525,...,2,126,0,0,DY+1,L,Yes,0.000000,0,0
3,0,10123/denis-rehak,1,2004,19.336111,25,0,3,3,0.120000,...,1,25,1,0,DY+1,L,Yes,0.000000,0,0
4,3,101430/nathan-walker,0,2013,19.605556,29,7,20,27,0.931034,...,1,29,1,0,DY+1,L,Yes,0.166667,12,1

In [36]:
# define function to convert shoots from string to int
def shoots_int(x):
    if x.SHOOTS == 'L':
        return 0
    elif x.SHOOTS == 'R':
        return 1

In [37]:
df['SHOOTS'] = df.apply(shoots_int, axis=1)
df.head()

,LEAGUE,PLAYER_ID,POSITION,SEASON,AGE_SEPT_15,GP,G,A,TP,PPG,...,SEASON_>20GP,CUM_GP,ONLY_1_SEASON,MIN_3_SEASONS,DY_STATUS,SHOOTS,DRAFTED,NHL_PPG,NHL_GP,NHL_DV
0,0,100577/richard-nejezchleb,0,2015,21.369444,49,20,31,51,1.040816,...,3,150,0,1,DY+3,0.0,Yes,0.000000,0,0
1,1,100867/jan-kostalek,1,2015,20.577778,57,7,36,43,0.754386,...,3,160,0,1,DY+2,1.0,Yes,0.000000,0,0
2,2,101221/dominik-kubalik,0,2014,19.066667,59,18,11,29,0.491525,...,2,126,0,0,DY+1,0.0,Yes,0.000000,0,0
3,0,10123/denis-rehak,1,2004,19.336111,25,0,3,3,0.120000,...,1,25,1,0,DY+1,0.0,Yes,0.000000,0,0
4,3,101430/nathan-walker,0,2013,19.605556,29,7,20,27,0.931034,...,1,29,1,0,DY+1,0.0,Yes,0.166667,12,1

In [40]:
# split outcomes into independent Df
outcomes = df['NHL_DV']
outcomes.head()

0    0
1    0
2    0
3    0
4    1
Name: NHL_DV, dtype: int64

In [42]:
# Create input factors w/o outcomes, drop ID
input_factors = df.drop(['NHL_DV', 'PLAYER_ID','DY_STATUS','DRAFTED','SEASON','NHL_PPG','NHL_GP'], axis = 1)
input_factors.head()

,LEAGUE,POSITION,AGE_SEPT_15,GP,G,A,TP,PPG,SEASON_NO,SEASON_>20GP,CUM_GP,ONLY_1_SEASON,MIN_3_SEASONS,SHOOTS
0,0,0,21.369444,49,20,31,51,1.040816,3,3,150,0,1,0.0
1,1,1,20.577778,57,7,36,43,0.754386,3,3,160,0,1,1.0
2,2,0,19.066667,59,18,11,29,0.491525,2,2,126,0,0,0.0
3,0,1,19.336111,25,0,3,3,0.120000,1,1,25,1,0,0.0
4,3,0,19.605556,29,7,20,27,0.931034,1,1,29,1,0,0.0

In [50]:
# Drop NaN and infinite numbers from set
df.replace([np.inf, -np.inf], np.nan).dropna()

,LEAGUE,PLAYER_ID,POSITION,SEASON,AGE_SEPT_15,GP,G,A,TP,PPG,...,SEASON_>20GP,CUM_GP,ONLY_1_SEASON,MIN_3_SEASONS,DY_STATUS,SHOOTS,DRAFTED,NHL_PPG,NHL_GP,NHL_DV
0,0,100577/richard-nejezchleb,0,2015,21.369444,49,20,31,51,1.040816,...,3,150,0,1,DY+3,0.0,Yes,0.000000,0,0
1,1,100867/jan-kostalek,1,2015,20.577778,57,7,36,43,0.754386,...,3,160,0,1,DY+2,1.0,Yes,0.000000,0,0
2,2,101221/dominik-kubalik,0,2014,19.066667,59,18,11,29,0.491525,...,2,126,0,0,DY+1,0.0,Yes,0.000000,0,0
3,0,10123/denis-rehak,1,2004,19.336111,25,0,3,3,0.120000,...,1,25,1,0,DY+1,0.0,Yes,0.000000,0,0
4,3,101430/nathan-walker,0,2013,19.605556,29,7,20,27,0.931034,...,1,29,1,0,DY+1,0.0,Yes,0.166667,12,1
5,1,1015/johnny-oduya,1,2001,19.955556,68,14,54,68,1.000000,...,1,68,1,0,DY+1,0.0,Yes,0.223529,850,1
6,2,10157/jordan-staal,0,2006,18.013889,68,28,40,68,1.000000,...,2,134,0,0,DY,0.0,Yes,0.571109,893,1
7,2,10158/jared-staal,0,2010,20.066667,59,12,37,49,0.830508,...,4,249,0,1,DY+2,1.0,Yes,0.000000,2,1
8,0,101581/shea-theodore,1,2015,20.116667,43,13,35,48,1.116279,...,4,253,0,1,DY+2,0.0,Yes,0.430052,193,1
9,0,101590/jackson-houck,0,2016,21.619444,56,20,33,53,0.946429,...,5,312,0,1,DY+3,1.0,Yes,0.000000,0,0
10,0,101642/tanner-faith,1,2016,20.944444,59,3,21,24,0.406780,...,2,133,0,0,DY+2,1.0,Yes,0.000000,0,0
11,3,10196/adam-burish,0,2002,19.691667,61,24,33,57,0.934426,...,1,61,1,0,DY+1,1.0,Yes,0.158730,378,1
12,3,101962/andrew-copp,0,2012,18.186111,18,3,7,10,0.555556,...,0,40,0,0,DY,0.0,Yes,0.286689,293,1
13,0,10197/matt-keith,0,2003,20.427778,56,27,28,55,0.982143,...,4,196,0,1,DY+2,1.0,Yes,0.185185,27,1
14,0,10200/d.j.-king,0,2004,20.216667,63,13,17,30,0.476190,...,3,183,0,1,DY+2,0.0,Yes,0.093220,118,1
15,2,10211/brad-richardson,0,2005,20.613889,68,41,56,97,1.426471,...,3,208,0,1,DY+2,0.0,Yes,0.308411,749,1
16,3,10212/paul-stastny,0,2004,18.716667,56,30,47,77,1.375000,...,2,113,0,0,DY,0.0,Yes,0.787185,874,1
17,1,10218/marc-edouard-vlasic,1,2006,19.458333,66,16,57,73,1.106061,...,3,177,0,1,DY+1,0.0,Yes,0.322280,965,1
18,1,10219/tomas-malec,1,2002,20.338889,51,14,32,46,0.901961,...,2,115,0,0,DY+2,0.0,Yes,0.043478,46,1
19,2,10221/nikita-alexeyev,0,2001,19.716667,64,31,41,72,1.125000,...,3,189,0,1,DY+1,0.0,Yes,0.237179,156,1
20,1,10226/bruno-gervais,1,2004,19.950000,23,4,6,10,0.434783,...,3,160,0,1,DY+1,1.0,Yes,0.208134,418,1
21,2,10228/shane-o-brien,1,2003,20.100000,62,16,26,42,0.677419,...,3,190,0,1,DY+2,0.0,Yes,0.171322,537,1
22,1,10233/aaron-johnson,1,2003,20.375000,57,10,51,61,1.070175,...,4,250,0,1,DY+2,0.0,Yes,0.213058,291,1
23,0,10235/gilbert-brule,0,2006,19.705556,27,23,15,38,1.407407,...,3,164,0,1,DY+1,1.0,Yes,0.317726,299,1
24,0,102378/ben-betker,1,2015,20.975000,64,6,25,31,0.484375,...,3,200,0,1,DY+2,0.0,Yes,0.000000,0,0
25,1,10247/keith-yandle,1,2006,20.016667,66,25,59,84,1.272727,...,1,66,1,0,DY+2,0.0,Yes,0.582139,907,1
26,3,10260/brandon-bochenski,0,2001,19.447222,55,47,33,80,1.454545,...,1,55,1,0,DY+1,1.0,Yes,0.435897,156,1
27,0,10261/nate-thompson,0,2005,20.944444,58,19,15,34,0.586207,...,4,253,0,1,DY+2,0.0,Yes,0.202296,697,1
28,2,10294/patrick-davis,0,2006,19.713889,60,35,33,68,1.133333,...,3,162,0,1,DY+1,1.0,Yes,0.111111,9,1
29,0,10298/david-bararuk,0,2003,20.302778,66,29,64,93,1.409091,...,4,212,0,1,DY+2,0.0,Yes,0.000000,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2780,2,9653/sergei-kostitsyn,0,2007,20.486111,59,40,91,131,2.220339,...,2,122,0,0,DY+2,0.0,Yes,0.498584,353,1
2781,0,9654/ivan-baranka,1,2005,20.322222,64,7,16,23,0.359375,...,2,122,0,0,DY+2,0.0,Yes,1.000000,1,1
2782,0,9657/konstantin-pushkaryov,0,2005,20.591667,69,22,30,52,0.753623,...,1,69,1,0,DY+2,0.0,Yes,0.294118,17,1
2783,1,9658/konstantin-zakharov,0,2004,19.369444,55,33,16,49,0.890909,...,1,55,1,0,DY+1,1.0,Yes,0.000000,0,0
2784,2,9661/ondrej-otcenas,0,2006,19.525000,50,5,6,11,0.220000,...,1,50,1,0,DY+1,0.0,Yes,0.000000,0,0
2785,3,9673/patrik-valcak,0,2005,20.747222,4,1,2,3,0.750000,...,0,61,0,0,DY+2,0.0,Yes,0.000000,0,0
2786,2,9676/ryan-jardine,0,2000,20.500000,65,43,34,77,1.184615,...,3,198,0,1,DY+2,0.0,Yes,0.250000,8,1
2787,3,96780/steven-santini,1,2013,18.522222,25,0,5,5,0.200000,...,2,61,0,0,DY,1.0,Yes,0.184211,114,1
2788,2,9683/kip-brennan,0,2001,21.050000,27,7,14,21,0.777778,...,4,162,0,1,DY+3,0.0,Yes,0.032787,61,1
2789,1,9685/ramzi-abid,0,2000,20.475000,72,67,91,158,2.194444,...,4,250,0,1,DY+2,0.0,Yes,0.441176,68,1
2790,1,96876/troy-vance,1,2014,21.119444,59,8,21,29,0.491525,...,4,206,0,1,DY+3,1.0,Yes,0.000000,0,0
2791,2,97341/connor-brown,0,2014,20.669444,68,45,83,128,1.882353,...,3,199,0,1,DY+2,1.0,Yes,0.391304,253,1
2792,2,97352/darnell-nurse,1,2015,20.613889,36,10,23,33,0.916667,...,4,221,0,1,DY+2,0.0,Yes,0.315412,279,1
2793,0,9739/stephen-peat,0,2000,20.513889,35,0,10,10,0.285714,...,4,202,0,1,DY+2,1.0,Yes,0.076923,130,1
2794,3,97590/will-butcher,1,2013,18.691667,26,3,10,13,0.500000,...,2,59,0,0,DY,0.0,Yes,0.465409,159,1
2795,3,97621/jaccob-slavin,1,2013,19.372222,62,5,28,33,0.532258,...,2,139,0,0,DY+1,0.0,Yes,0.372168,309,1
2796,1,97663/marc-olivier-roy,0,2015,20.861111,59,26,24,50,0.847458,...,4,229,0,1,DY+2,0.0,Yes,0.000000,0,0
2797,0,97787/madison-bowey,1,2015,20.397222,58,17,43,60,1.034483,...,4,256,0,1,DY+2,1.0,Yes,0.217822,101,1
2798,1,97908/mackenzie-weegar,1,2014,20.702778,61,12,47,59,0.967213,...,2,123,0,0,DY+2,1.0,Yes,0.181102,127,1
2799,2,97951/jordan-subban,1,2015,20.533333,63,25,27,52,0.825397,...,4,253,0,1,DY+2,1.0,Yes,0.000000,0,0
2800,3,97957/brandon-montour,1,2015,21.427778,17,6,15,21,1.235294,...,0,77,0,0,DY+3,1.0,Yes,0.386243,189,1
2801,2,98300/radek-faksa,0,2014,20.683333,59,21,27,48,0.813559,...,3,160,0,1,DY+2,0.0,Yes,0.378947,285,1
2802,2,98663/tom-wilson,0,2013,19.461111,48,23,35,58,1.208333,...,3,125,0,1,DY+1,1.0,Yes,0.317181,454,1
2803,1,98665/anthony-duclair,0,2015,20.052778,26,15,19,34,1.307692,...,4,203,0,1,DY+2,0.0,Yes,0.425087,287,1
2804,1,98666/jeremy-gregoire,0,2015,20.027778,32,20,21,41,1.281250,...,4,220,0,1,DY+2,1.0,Yes,0.000000,0,0
2805,2,99036/nick-ritchie,0,2015,19.777778,48,29,33,62,1.291667,...,4,212,0,1,DY+1,0.0,Yes,0.365854,246,1
2806,2,99041/joseph-blandisi,0,2015,21.158333,68,52,60,112,1.647059,...,4,246,0,1,DY+3,0.0,Yes,0.325000,80,1
2807,0,9905/layne-ulmer,0,2001,21.002778,68,63,56,119,1.750000,...,4,261,0,1,DY+3,0.0,Yes,0.000000,1,1
2808,1,9920/jason-king,0,2002,21.002778,61,63,36,99,1.622951,...,3,186,0,1,DY+3,0.0,Yes,0.389831,59,1
2809,1,99204/nathan-mackinnon,0,2013,18.038889,44,32,43,75,1.704545,...,2,102,0,0,DY,1.0,Yes,0.881579,456,1

In [58]:
# Check for null - there shouldn't be any
pd.isnull(X_train).sum() > 0

LEAGUE           False
POSITION         False
AGE_SEPT_15      False
GP               False
G                False
A                False
TP               False
PPG              False
SEASON_NO        False
SEASON_>20GP     False
CUM_GP           False
ONLY_1_SEASON    False
MIN_3_SEASONS    False
SHOOTS            True
dtype: bool

In [51]:
# Assign X (data) and y (target)
X = input_factors
y = outcomes
print(X.shape, y.shape)

(2810, 14) (2810,)

In [52]:
# split data into test/train
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1, stratify=y)

In [53]:
# import llogistic reg from sklean
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression()
classifier

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [54]:
LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [55]:
# run regression
classifier.fit(X_train, y_train)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)

ValueError: Input contains NaN, infinity or a value too large for dtype('float64').