This is a preliminary cleaning and splitting of the data. I want to work with the data as a whole as well as certain subsets, such as only players who were drafted.

In [1]:
 %matplotlib notebook

In [2]:
#Dependencies
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import os

In [3]:
#Import CSV
juniors_df=pd.read_csv('na_juniors_99to19.csv')
juniors_df.head()

,LEAGUE,PLAYER_ID,POSITION,SEASON,AGE_SEPT_15,GP,G,A,TP,PPG,...,SEASON_>20GP,CUM_GP,ONLY_1_SEASON,MIN_3_SEASONS,DOB,DY_STATUS,SHOOTS,DRAFTED,NHL_PPG,NHL_GP
0,WHL,100056/tye-hand,D,2013,18.252778,31,0,2,2,0.060000,...,1,31,1,0,1995-06-14,DY,L,No,0.0,0
1,OHL,100141/sean-thompson,F,2002,18.625000,38,0,4,4,0.110000,...,1,38,0,1,1984-01-31,DY,L,No,0.0,0
2,OHL,100141/sean-thompson,F,2003,19.625000,61,6,5,11,0.180328,...,2,99,0,1,1984-01-31,DY+1,L,No,0.0,0
3,OHL,100141/sean-thompson,F,2004,20.625000,38,6,5,11,0.289474,...,3,137,0,1,1984-01-31,DY+2,L,No,0.0,0
4,USHL,100151/stanislav-dzakhov,F,2012,19.497222,44,9,5,14,0.318182,...,1,44,0,0,1993-03-16,DY+1,R,No,0.0,0

In [27]:
# Drop columns that will not be used & duplicates
juniors_df=juniors_df.drop(['DOB'],axis=1)

juniors_df=juniors_df.drop_duplicates(keep='last', subset='PLAYER_ID')

KeyError: "['DOB'] not found in axis"

In [8]:
#player count and unique, these are the same because duplicates were dropped except for the last season in juniors
juniors_df['PLAYER_ID'].nunique()
# 13,997 Unique players
juniors_df['PLAYER_ID'].count()
#  35,251 entries

35251

In [19]:
# create a unique DF for only players who are drafted

drafted_df = juniors_df[juniors_df['DRAFTED']=='Yes']
drafted_df.head()

,LEAGUE,PLAYER_ID,POSITION,SEASON,AGE_SEPT_15,GP,G,A,TP,PPG,...,SEASON_>20GP,CUM_GP,ONLY_1_SEASON,MIN_3_SEASONS,DOB,DY_STATUS,SHOOTS,DRAFTED,NHL_PPG,NHL_GP
29,WHL,100577/richard-nejezchleb,F,2013,19.369444,35,11,13,24,0.685714,...,1,35,0,1,1994-05-02,DY+1,L,Yes,0.0,0
30,WHL,100577/richard-nejezchleb,F,2014,20.369444,66,32,25,57,0.863636,...,2,101,0,1,1994-05-02,DY+2,L,Yes,0.0,0
31,WHL,100577/richard-nejezchleb,F,2015,21.369444,49,20,31,51,1.040816,...,3,150,0,1,1994-05-02,DY+3,L,Yes,0.0,0
51,QMJHL,100867/jan-kostalek,D,2013,18.577778,48,5,13,18,0.375000,...,1,48,0,1,1995-02-17,DY,R,Yes,0.0,0
52,QMJHL,100867/jan-kostalek,D,2014,19.577778,55,5,22,27,0.490909,...,2,103,0,1,1995-02-17,DY+1,R,Yes,0.0,0

In [20]:
# we have data for 2810 players who were drafted out of a total of pool of 13,997 players
drafted_df['PLAYER_ID'].nunique()

2810

In [25]:
#

,SEASON,AGE_SEPT_15,GP,G,A,TP,PPG,SEASON_NO,SEASON_>20GP,CUM_GP,ONLY_1_SEASON,MIN_3_SEASONS,NHL_PPG,NHL_GP
count,8597.000000,8597.000000,8597.000000,8597.000000,8597.000000,8597.000000,8597.000000,8597.000000,8597.000000,8597.000000,8597.000000,8597.000000,8597.000000,8597.000000
mean,2008.399674,19.151417,56.122019,15.113644,24.328603,39.443294,0.686249,2.292311,2.160405,128.519949,0.049436,0.801326,0.111267,99.910318
std,5.959678,1.216735,14.867912,12.613099,16.251229,26.960646,0.420776,1.178488,1.211940,74.847453,0.216789,0.399025,0.191736,211.741603
min,1996.000000,15.858333,1.000000,0.000000,0.000000,1.000000,0.020000,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000
25%,2003.000000,18.266667,52.000000,5.000000,11.000000,17.000000,0.344828,1.000000,1.000000,62.000000,0.000000,1.000000,0.000000,0.000000
50%,2008.000000,19.225000,61.000000,12.000000,22.000000,35.000000,0.628571,2.000000,2.000000,122.000000,0.000000,1.000000,0.000000,0.000000
75%,2013.000000,20.161111,66.000000,23.000000,35.000000,57.000000,0.961538,3.000000,3.000000,186.000000,0.000000,1.000000,0.186667,75.000000
max,2019.000000,21.705556,81.000000,74.000000,115.000000,186.000000,2.952381,6.000000,6.000000,357.000000,1.000000,1.000000,3.000000,1249.000000

In [9]:
# #create unique df for each league
# ohl_players=juniors_df[juniors_df['LEAGUE']=='OHL']

# whl_players=juniors_df[juniors_df['LEAGUE']=='WHL']

# ushl_players=juniors_df[juniors_df['LEAGUE']=='USHL']

# qmjhl_players=juniors_df[juniors_df['LEAGUE']=='QMJHL']

In [24]:
# 
avg_gp = drafted_df['CUM_GP'].mean()
avg_nhl_gp = drafted_df['NHL_GP'].mean()
print(f'Average Juniors Games Played: {avg_gp}')
print(f'Average NHL Games Played: {avg_nhl_gp}')

Average Juniors Games Played: 128.5199488193556
Average NHL Games Played: 99.91031755263464

In [ ]:
#drafted only Df